"""Initial baseline

Revision ID: 64a976086bf0
Revises: 
Create Date: 2026-06-28 15:20:03.916957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64a976086bf0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('response_body', sa.String(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('conf', sa.String(), server_default='{}', nullable=False),
    sa.Column('templates', sa.String(), server_default='{}', nullable=False),
    sa.Column('pending_review_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('conf', sa.String(), server_default='{}', nullable=False),
    sa.Column('algoconf', sa.String(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('base_for', sa.String(length=20), nullable=False),
    sa.Column('fields', sa.String(), server_default='{}', nullable=False),
    sa.Column('data', sa.String(), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='Active', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_units',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('unit_type', sa.String(length=20), nullable=False),
    sa.Column('position', sa.String(), server_default='a', nullable=False),
    sa.Column('due', sa.BigInteger(), nullable=True),
    sa.Column('last_review', sa.BigInteger(), nullable=True),
    sa.Column('slot', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unit_data', sa.String(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('learning_unit_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('reviewed_at', sa.BigInteger(), nullable=False),
    sa.Column('duration', sa.BigInteger(), nullable=False),
    sa.Column('type_review_data', sa.String(), server_default='{}', nullable=False),
    sa.Column('state_before', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['learning_unit_id'], ['learning_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('learning_units')
    op.drop_table('nodes')
    op.drop_table('collections')
    op.drop_table('users')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
