#!/bin/bash
# Run the same checks as CI, locally, before tagging a release.
# Usage: ./scripts/preflight.sh
 
set -e
 
cd "$(dirname "$0")/.."
 
echo "==> Setting up config (if needed)..."
if [ ! -f "config.json" ]; then
    cp config.json.example config.json
fi
 
echo ""
echo "==> Running pytest..."
./env/bin/pytest tests/
 
echo ""
echo "==> Running pip-audit..."
./env/bin/pip install --quiet pip-audit
# NOTE: no --fix here. requirements.txt is generated by pip-compile from
# requirements.in — pip-audit --fix would edit requirements.txt directly and
# desync it from requirements.in. If vulnerabilities are found below, fix
# them by editing requirements.in (pin a minimum safe version) and running:
#   pip-compile requirements.in --upgrade-package <name>
./env/bin/pip install -r requirements.txt -r requirements-dev.txt
 
echo ""
echo "==> Running npm audit..."
npm audit --prefix node_deps --audit-level=high
 
echo ""
echo "==> All checks passed. Safe to tag a release."
echo "    Next: ./scripts/bump_version.sh <version>"
 
